# Generated by Django 6.0.6 on 2026-06-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
