# Generated by Django 6.0.6 on 2026-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
