# Generated by Django 6.0.6 on 2026-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_google_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
