# Generated by Django 6.0.6 on 2026-06-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
