# Generated by Django 6.0.6 on 2026-06-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_old_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
