# Generated by Django 6.0.6 on 2026-06-16 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_remaining_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_json', models.JSONField(default=dict)),
                ('store_name', models.CharField(blank=True, default='', max_length=255)),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_bill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
